### ISSUE TITLE
[Solved] Error with "informant read --all"

### ISSUE THREAD

**Issue by R8s6** [bradford-smith94/informant#30]
Hi,

I got this error on 4 different Arch machines, all having the same output:

```
$ informant read --all
Traceback (most recent call last):
  File "/usr/bin/informant", line 33, in <module>
    sys.exit(load_entry_point('informant==0.4.2', 'console_scripts', 'informant')())
  File "/usr/lib/python3.9/site-packages/informant/informant.py", line 178, in main
    run()
  File "/usr/lib/python3.9/site-packages/informant/informant.py", line 171, in run
    read_cmd(feed)
  File "/usr/lib/python3.9/site-packages/informant/informant.py", line 120, in read_cmd
    entry.mark_as_read(entry)
TypeError: mark_as_read() takes 1 positional argument but 2 were given
```
This happened a couple of weeks ago, around maybe v0.4 update?

The user is in the `informant`group.

Also:
```
$ ls -ld /var/cache/informant
drwxrwsr-x 4 root informant 4096 Feb  7 11:08 /var/cache/informant
```

Could you please kindly take a look to see if it's a bug?

Thank you.

**Comment by R8s6** [comment]
that was fast, thanks a lot!
