### ISSUE TITLE
Fails after Python 3.10 update

### ISSUE THREAD

**Issue by Strykar** [bradford-smith94/informant#39]
```
:: Running pre-transaction hooks...
(1/1) Checking Arch News with Informant ...
Traceback (most recent call last):
  File "/usr/bin/informant", line 33, in <module>
    sys.exit(load_entry_point('informant==0.4.5', 'console_scripts', 'informant')())
  File "/usr/bin/informant", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 919, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 518, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for informant
error: command failed to execute correctly
error: failed to commit transaction (failed to run transaction hooks)
Errors occurred, no packages were upgraded.
Done - Press enter to exit
```

**Comment by CyrusYip** [comment]
Rebuilding solves the problem.

```
sudo pacman -R informant
yay -S informant
```

**Comment by Strykar** [comment]
You're right, closing.
