### ISSUE TITLE
Use psutil instead of shelling out to ps

### ISSUE THREAD

**Issue by rpdelaney** [bradford-smith94/informant#44]
The current code uses the subprocess module to invoke `ps` commands for process management. We should consider replacing these subprocess calls with the `psutil` library, which is not part of the standard library but provides a more robust interface for interacting with system processes.

Using `psutil` over subprocess to call `ps` has some advantages. Directly using `psutil` avoids the risks associated with parsing shell command output, which can be unstable. You have no mechanism to check or pin external shell dependencies like you do with python modules.

**Comment by rpdelaney** [comment]
I encountered this problem trying to write a Containerfile for informant:

```python-traceback
error: process ID out of range

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
Traceback (most recent call last):
  File "/usr/sbin/informant", line 33, in <module>
    sys.exit(load_entry_point('informant==0.5.0', 'console_scripts', 'informant')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/informant-0.5.0-py3.11.egg/informant/informant.py", line 170, in main
  File "/usr/lib/python3.11/site-packages/informant-0.5.0-py3.11.egg/informant/informant.py", line 74, in check_cmd
  File "/usr/lib/python3.11/site-packages/informant-0.5.0-py3.11.egg/informant/ui.py", line 79, in running_from_pacman
  File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ps', '-p', '0', '-o', 'comm=']' returned non-zero exit status 1.
```

Glancing at the code I think I see how this might be fixed in the short-term, but psutil solves the problem once and for all.

Here's the Containerfile that generated the error, for reference:
```Dockerfile
FROM archlinux:base

RUN pacman --noconfirm --quiet -Syu procps-ng python python-pip python-virtualenv python-setuptools

WORKDIR /usr/src/app

COPY requirements.txt setup.py ./
COPY informant/ ./informant/

RUN python -m venv .venv
ENV PATH="/usr/src/app/.venv/bin:$PATH"

RUN pip install \
    --no-cache-dir \
    --no-color \
    --disable-pip-version-check \
    --isolated \
    --progress-bar off \
    --compile \
    --requirement requirements.txt && \
    python setup.py build && \
    python setup.py install --optimize=1

ENTRYPOINT ["informant"]
```

**Comment by rpdelaney** [comment]
Thanks for the fix @bradford-smith94 . Please feel free to use the `Containerfile`, which I release under the MIT license. I would send a PR but I have moved on to other hyperfixations.

**Comment by bradford-smith94** [comment]
Thanks! Sorry I didn't get around to this sooner.
